name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.UPSTREAM_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "sync-bot"
          git config user.email "sync-bot@users.noreply.github.com"

      # ⭐ Protect workflow during merge
      - name: Protect workflow files
        run: |
          git config --global merge.ours.driver true

      - name: Add upstream
        run: |
          git remote add upstream https://x-access-token:${{ secrets.UPSTREAM_TOKEN }}@github.com/c1ph3r-1337/Vault.git
          git fetch upstream

      - name: Merge upstream
        run: |
          git checkout main
          git merge upstream/main --no-edit || true
          git push origin main
