name: Trigger Fork Sync

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch fork sync event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.FORK_TRIGGER_TOKEN }}
          repository: MannatBehal1608/Vault
          event-type: upstream-sync
